spring.application.name=isopod
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.core.codec=DEBUG
logging.level.org.springframework.http=DEBUG
logging.level.org.springframework.boot.actuate.endpoint.web=DEBUG
logging.level.org.springframework.boot.web.servlet.ServletContextInitializerBeans=DEBUG
logging.level.org.thymeleaf=DEBUG

# spring.thymeleaf.prefix=templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
spring.web.resources.static-locations=classpath:/static/
spring.main.web-application-type=servlet
